# Site
repository: LoaiSaadi/cv
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Loai Saadi
title: Computer Science Student
email: saadiloai@gmail.com
# Removed website line

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: null
github_username:  LoaiSaadi
# stackoverflow_username: null
# dribbble_username: null
# facebook_username: null
# flickr_username: null
# instagram_username: null
linkedin_username: loai-saadi
# leetcode_username: null
# xing_username: null
# pinterest_username: null
# youtube_username: null
# googleplus_username: null
# orcid_username: null

# Additional icon links
additional_links:
- title: null
  icon: fas fa-globe
  url: null
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_profile_image: images/profile-picture.png
about_content: | 
  Hi, my name is Loai Saadi, a computer science student at the University of Haifa. I have experience in full-stack development, software engineering, and software development. I'm currently expanding my knowledge in AI and web development.

  I am most skilled in: <mark>Python</mark>, <mark>Java</mark>, <mark>JavaScript</mark>, and <mark>React</mark>.

content:
  - title: Technical Skills
    layout: list
    content:
      - layout: left
        title: Technical Skills
        quote: >
          A summary of my technical skills and proficiencies.
        description: |
          • Proficient in: C, Python, Java, JavaScript, React, Node.js, Express, VS Code, GitHub, Windows.  
          • Experienced with: C++, C#, OOP, RESTful API, HTML, CSS, MySQL, MongoDB.  
          • Familiar with: Postman, MATLAB, Heroku, Linux.  

  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Software Engineering, High School Test System
        link: github.com/LoaiSaadi/High-School-Test-System
        # link_text: Project Website
        additional_links:
          - title: LoaiSaadi/High-School-Test-System
            icon: fab fa-github
            url: https://github.com/LoaiSaadi/High-School-Test-System
        quote: >
          Built a comprehensive system for managing high school tests, grading, and login authentication.
        description: |
          Collaborated in a four-member team to design server and client interfaces, manage exams and grading databases, and establish user login access. Utilized IntelliJ with Java, OCSF, GUI, ORM, and integrated database solutions for effective application development.

      - layout: top-middle
        title: Parkly (Hasoub Hackathon)
        quote: >
          Created a smart parking solution to help ease traffic congestion.
        description: |
          Collaborated in a four-member team to develop a parking tracking model with Parkly, enhancing traffic flow and offering a 40% student discount.

      - layout: top-middle
        title: DevQALink (Scheduler Team)
        link: github.com/moslem-asaad/DevQALink
        additional_links:
          - title: moslem-asaad/DevQALink
            icon: fab fa-github
            url: https://github.com/moslem-asaad/DevQALink
        quote: >
          DevQALink connects QA and development teams for test scheduling, reporting, and automated bug creation.
        description: |
          Collaborated as part of a four-member team to develop DevQALink, a framework connecting QA and development teams. Designed a test management system that enables users to schedule one-time or recurring tests, prioritize jobs, and allocate resources for seamless execution.

      - layout: top-middle
        title: DevQALink
        link: github.com/LoaiSaadi/DevQALink
        additional_links:
          - title: LoaiSaadi/DevQALink
            icon: fab fa-github
            url: https://github.com/LoaiSaadi/DevQALink
        quote: >
          Completed independently a test management framework to automate job scheduling and resource allocation.
        description: |
          This site, built with the MERN stack and MVC architecture in collaboration with Dell Technologies, facilitates automated test executions and job scheduling. It features JWT authentication, email notifications, and Jira bug ticketing, while incorporating Dell's branding through a cohesive blue, white, and grey design.

  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Haifa
        caption: 2021 - Present
        sub_title: BSc Computer Science
        quote: >
          Expanding knowledge in software development, AI, and web technologies.
        description: |
          Courses include Intro to Computer Science (98), Algorithms (87), Software Engineering (94), and Assembly (98).

  - title: Certifications
    layout: list
    content:
      - layout: left
        title: Python Mega Course, Learn Python in 60 Days
        link: udemy.com/certificate/UC-96ebabb9-957c-4abd-8ce6-fca3f2e9026d/
        quote: >
          This certificate verifies that Loai Saadi successfully completed the course on 10/05/2024 as taught by Ardit Sulce on Udemy.
        description: |
          Completed a Python course, transitioning from beginner to proficient programmer by building 20 applications. Gained expertise in web development, automation, data analysis, machine learning, and tools like Git, Flask, and Django, creating a portfolio to showcase skills. 

  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interest in software development, I enjoy:
      - Tutoring children in the "Perach" Program
      - Learning about AI and blockchain technologies
      - Developing projects and applications to solve real-world problems

  - title: Languages
    layout: list
    content:
      - layout: left
        title: Languages
        quote: >
          My language proficiencies are as follows:
        description: |
          • Arabic – Mother tongue  
          • Hebrew – Fluent  
          • English - Fluent  

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
